# Customer Churn prediction

### Load Dataset

In [65]:
import pandas as pd

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

### Data Preprocessing

In [66]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [67]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [68]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [70]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [71]:
df = df.dropna()

In [72]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [73]:
# Sabhi categorical columns
cat_cols = df.select_dtypes(include="object").columns

for col in cat_cols:
    print(f"\n===== {col} =====")
    print(df[col].value_counts())

===== customerID =====
customerID
7590-VHVEG    1
0265-PSUAE    1
2956-GGUCQ    1
6008-NAIXK    1
5956-YHHRX    1
             ..
7874-ECPQJ    1
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
3186-AJIEK    1
Name: count, Length: 7032, dtype: int64

===== gender =====
gender
Male      3549
Female    3483
Name: count, dtype: int64

===== Partner =====
Partner
No     3639
Yes    3393
Name: count, dtype: int64

===== Dependents =====
Dependents
No     4933
Yes    2099
Name: count, dtype: int64

===== PhoneService =====
PhoneService
Yes    6352
No      680
Name: count, dtype: int64

===== MultipleLines =====
MultipleLines
No                  3385
Yes                 2967
No phone service     680
Name: count, dtype: int64

===== InternetService =====
InternetService
Fiber optic    3096
DSL            2416
No             1520
Name: count, dtype: int64

===== OnlineSecurity =====
OnlineSecurity
No                     3497
Yes                    2015
No internet service    1520
Name: count, dtype: int64

===== OnlineBackup =====
OnlineBackup
No                     3087
Yes                    2425
No internet service    1520
Name: count, dtype: int64

===== DeviceProtection =====
DeviceProtection
No                     3094
Yes                    2418
No internet service    1520
Name: count, dtype: int64

===== TechSupport =====
TechSupport
No                     3472
Yes                    2040
No internet service    1520
Name: count, dtype: int64

===== StreamingTV =====
StreamingTV
No                     2809
Yes                    2703
No internet service    1520
Name: count, dtype: int64

===== StreamingMovies =====
StreamingMovies
No                     2781
Yes                    2731
No internet service    1520
Name: count, dtype: int64

===== Contract =====
Contract
Month-to-month    3875
Two year          1685
One year          1472
Name: count, dtype: int64

===== PaperlessBilling =====
PaperlessBilling
Yes    4168
No     2864
Name: count, dtype: int64

===== PaymentMethod =====
PaymentMethod
Electronic check             2365
Mailed check                 1604
Bank transfer (automatic)    1542
Credit card (automatic)      1521
Name: count, dtype: int64

===== Churn =====
Churn
No     5163
Yes    1869
Name: count, dtype: int64

In [74]:
df = df.drop("customerID",axis=1)

In [75]:
cat_cols = df.select_dtypes(include="object").columns

df = pd.get_dummies(
    df,
    columns=cat_cols,
    drop_first=True
)
df.shape

(7032, 31)

In [ ]:
### Split and train data

In [76]:

# Features and Target
X = df.drop("Churn_Yes", axis=1)
y = df["Churn_Yes"]

In [77]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.ensemble import (
    BaggingClassifier,
    RandomForestClassifier,
    AdaBoostClassifier,
    GradientBoostingClassifier
)

from xgboost import XGBClassifier

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Models
models = {
    "Bagging": BaggingClassifier(
        n_estimators=100,
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),

    "AdaBoost": AdaBoostClassifier(
        n_estimators=100,
        random_state=42
    ),

    "Gradient Boosting": GradientBoostingClassifier(
        n_estimators=100,
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        n_estimators=100,
        random_state=42,
        eval_metric="logloss"
    )
}

print("===== Model Comparison =====\n")

for name, model in models.items():

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Accuracy
    acc = accuracy_score(y_test, y_pred)

    print(f"{name}: {acc:.4f}")

===== Model Comparison =====

Bagging: 0.7903
Random Forest: 0.7854
AdaBoost: 0.7918
Gradient Boosting: 0.7896
XGBoost: 0.7740